version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: soundbird
      POSTGRES_PASSWORD: soundbirdpass
      POSTGRES_DB: soundbird_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
