"""normalize detections with recording_id FK

Revision ID: 6fd71d5611fd
Revises: 757e20a2f1b1
Create Date: 2025-07-29 14:03:42.874087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fd71d5611fd'
down_revision: Union[str, None] = '757e20a2f1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('recording_id', sa.Integer(), nullable=False))
    op.alter_column('detections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_detections_image_path', table_name='detections')
    op.create_index(op.f('ix_detections_detection_time'), 'detections', ['detection_time'], unique=False)
    op.create_index(op.f('ix_detections_scientific_name'), 'detections', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_detections_species'), 'detections', ['species'], unique=False)
    op.create_foreign_key(
    'fk_detections_recording_id',  # Explicit constraint name
    'detections',                  # Source table
    'recordings',                  # Referenced table
    ['recording_id'],              # Source column(s)
    ['id']                         # Referenced column(s)
    )
    op.drop_column('detections', 'lon')
    op.drop_column('detections', 'file_name')
    op.drop_column('detections', 'lat')
    op.drop_column('detections', 'image_path')
    op.drop_column('detections', 'recording_datetime')
    op.add_column('recordings', sa.Column('recording_datetime', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'recording_datetime')
    op.add_column('detections', sa.Column('recording_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('detections', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('detections', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('detections', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('detections', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('fk_detections_recording_id', 'detections', type_='foreignkey')
    op.drop_index(op.f('ix_detections_species'), table_name='detections')
    op.drop_index(op.f('ix_detections_scientific_name'), table_name='detections')
    op.drop_index(op.f('ix_detections_detection_time'), table_name='detections')
    op.create_index('ix_detections_image_path', 'detections', ['image_path'], unique=False)
    op.alter_column('detections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('detections', 'recording_id')
    # ### end Alembic commands ###
